//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTWeb.Assets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLTWeb.Assets.Resources.ResStrings", typeof(ResStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Class:.
        /// </summary>
        public static string AI_Class_Label {
            get {
                return ResourceManager.GetString("AI_Class_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Name:.
        /// </summary>
        public static string AI_Name_Label {
            get {
                return ResourceManager.GetString("AI_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Class Name:.
        /// </summary>
        public static string AIClassName_Label {
            get {
                return ResourceManager.GetString("AIClassName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Method:.
        /// </summary>
        public static string AppMethod_Label {
            get {
                return ResourceManager.GetString("AppMethod_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS Number:.
        /// </summary>
        public static string CASNum_Label {
            get {
                return ResourceManager.GetString("CASNum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Use:.
        /// </summary>
        public static string CropUse_Label {
            get {
                return ResourceManager.GetString("CropUse_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division:.
        /// </summary>
        public static string Division_Label {
            get {
                return ResourceManager.GetString("Division_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email_Label {
            get {
                return ResourceManager.GetString("Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event:.
        /// </summary>
        public static string Event_Label {
            get {
                return ResourceManager.GetString("Event_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string FirstName_Label {
            get {
                return ResourceManager.GetString("FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulation:.
        /// </summary>
        public static string Formulation_Label {
            get {
                return ResourceManager.GetString("Formulation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE INGREDIENT.
        /// </summary>
        public static string IndexAI {
            get {
                return ResourceManager.GetString("IndexAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI CLASS.
        /// </summary>
        public static string IndexAIClass {
            get {
                return ResourceManager.GetString("IndexAIClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION METHOD.
        /// </summary>
        public static string IndexAppMethod {
            get {
                return ResourceManager.GetString("IndexAppMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROP USE.
        /// </summary>
        public static string IndexCropUse {
            get {
                return ResourceManager.GetString("IndexCropUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIVISION.
        /// </summary>
        public static string IndexDivision {
            get {
                return ResourceManager.GetString("IndexDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENT.
        /// </summary>
        public static string IndexEvent {
            get {
                return ResourceManager.GetString("IndexEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORMULATION.
        /// </summary>
        public static string IndexFormulation {
            get {
                return ResourceManager.GetString("IndexFormulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIMITATION CODE.
        /// </summary>
        public static string IndexLimitCode {
            get {
                return ResourceManager.GetString("IndexLimitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZATION.
        /// </summary>
        public static string IndexOrganization {
            get {
                return ResourceManager.GetString("IndexOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT.
        /// </summary>
        public static string IndexProduct {
            get {
                return ResourceManager.GetString("IndexProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIES.
        /// </summary>
        public static string IndexSpp {
            get {
                return ResourceManager.GetString("IndexSpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string LastName_Label {
            get {
                return ResourceManager.GetString("LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation:.
        /// </summary>
        public static string Limitation_Label {
            get {
                return ResourceManager.GetString("Limitation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation Code:.
        /// </summary>
        public static string LimitationCode_Label {
            get {
                return ResourceManager.GetString("LimitationCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization:.
        /// </summary>
        public static string Org_Label {
            get {
                return ResourceManager.GetString("Org_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Ingredient.
        /// </summary>
        public static string PartsAI {
            get {
                return ResourceManager.GetString("PartsAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Use.
        /// </summary>
        public static string PartsCropUse {
            get {
                return ResourceManager.GetString("PartsCropUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string PartsProduct {
            get {
                return ResourceManager.GetString("PartsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC Code:.
        /// </summary>
        public static string PCCode_Label {
            get {
                return ResourceManager.GetString("PCCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string Phone_Label {
            get {
                return ResourceManager.GetString("Phone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name:.
        /// </summary>
        public static string ProductName_Label {
            get {
                return ResourceManager.GetString("ProductName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number:.
        /// </summary>
        public static string RegNum_Label {
            get {
                return ResourceManager.GetString("RegNum_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string Role_Label {
            get {
                return ResourceManager.GetString("Role_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Name:.
        /// </summary>
        public static string SppCommonName_Label {
            get {
                return ResourceManager.GetString("SppCommonName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family:.
        /// </summary>
        public static string SppFamily_Label {
            get {
                return ResourceManager.GetString("SppFamily_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        public static string SppGroup_Label {
            get {
                return ResourceManager.GetString("SppGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Name:.
        /// </summary>
        public static string SppScientName_Label {
            get {
                return ResourceManager.GetString("SppScientName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa:.
        /// </summary>
        public static string SppTaxa_Label {
            get {
                return ResourceManager.GetString("SppTaxa_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string UserName_Label {
            get {
                return ResourceManager.GetString("UserName_Label", resourceCulture);
            }
        }
    }
}
